<?php

namespace Ticme\BackBundle\Repository;

/**
 * OrderingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderingRepository extends \Doctrine\ORM\EntityRepository
{
    public function byFacture($user){
        $qb = $this->createQueryBuilder('o')
            ->select('o')
            ->where('o.user = :user')
            ->andWhere('o.validated = 1')
            ->andWhere('o.reference != 0')
            ->orderBy('o.id')
            ->setParameter('user', $user)
        ;
        return $qb->getQuery()->getResult();
    }

}
